### ISSUE TITLE
ApiErrors: Backend Error

### ISSUE THREAD

**Issue by hrovira** [GoogleCloudPlatform/gcloud-node#1108]
Getting a generic ```Backend Error```. Not sure if its worth verifying the status of datastore.  
I was accessing datastore from my dev box, as well as from GCE. 

I can still view Datastore Entities from https://console.developers.google.com/datastore/entities/query, but I also saw a ```Backend Error``` popup when I tried to access the "Admin" section.

Also saw messages on AppEngine admin logs, but now I can't find them, not sure if related.

Message below from GCE:
```
    at new util.ApiError (.../node_modules/gcloud/lib/common/util.js:92:10)
    at Object.parseHttpRespMessage (.../node_modules/gcloud/lib/common/util.js:134:33)
    at Request._callback (.../node_modules/gcloud/lib/datastore/request.js:813:31)
    at Request.self.callback (.../node_modules/gcloud/node_modules/request/request.js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (.../node_modules/gcloud/node_modules/request/request.js:1036:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (.../node_modules/gcloud/node_modules/request/request.js:963:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```

Message below from my dev box:

```
ApiError: Service Unavailable
    at new util.ApiError (.../node_modules/gcloud/lib/common/util.js:92:10)
    at Object.parseHttpRespMessage (.../node_modules/gcloud/lib/common/util.js:134:33)
    at Request._callback (.../node_modules/gcloud/lib/datastore/request.js:813:31)
    at Request.self.callback (.../node_modules/gcloud/node_modules/request/request.js:199:22)
    at Request.<anonymous> (.../node_modules/gcloud/node_modules/request/request.js:1036:10)
    at IncomingMessage.<anonymous> (.../node_modules/gcloud/node_modules/request/request.js:963:12)
    at _stream_readable.js:908:16
```

PS
Don't know if this is the appropriate forum for these types of issues.

```
"gcloud": "^0.27.0",
```

**Comment by hrovira** [comment]
Its responsive now

**Comment by stephenplusplus** [comment]
Sounds like an API hiccup, but glad to hear it's working smoothly again.

> Don't know if this is the appropriate forum for these types of issues.

@jgeewax is there a good place for users to submit issues like this (and [this](https://github.com/GoogleCloudPlatform/gcloud-common/issues/51))?

**Comment by hrovira** [comment]
Appreciate the help! This didn't seem like a post for stackoverflow either... 

I found a more appropriate link in the [support documentation](https://cloud.google.com/datastore/docs/support)

__Non-paid support customers__
[Submit a Cloud Datastore production issue](https://docs.google.com/a/google.com/forms/d/1ZBczgbmn1spg7GvaQnCoY-Zhxi4d6YHMdLMV6cPixrk/viewform)
