### ISSUE TITLE
require('gcloud')  crashing node app

### ISSUE THREAD

**Issue by musicalshore** [GoogleCloudPlatform/gcloud-node#1129]
http://stackoverflow.com/questions/35414629/gcloud-causing-node-app-to-crash

My app suddenly started crashing and I've narrowed it down to a require('gcloud') on a server controller. This happened after merging from another branch. I've looked and looked, tried deleting and reinstalling all node_modules and nothing has helped. There are no differences between the package.json files on either branch.

`app/services/node_modules/node-forge/js/forge.js:41
          mods[i](forge);`
                 ^

    TypeError: mods[i] is not a function
        at Object.module.exports (/Users/myhome/Development/app/services/node_modules/node-forge/js/forge.js:41:14)
        at defineFunc (/Users/myhome/Development/app/services/node_modules/node-forge/js/forge.js:47:10)
        at Object.<anonymous> (/Users/myhome/Development/app/services/node_modules/node-forge/js/forge.js:90:14)
        at global.define (/Users/myhome/Development/app/services/node_modules/amd-loader/amd-loader.js:79:28)
        at define (/Users/myhome/Development/app/services/node_modules/node-forge/js/forge.js:57:17)
        at /Users/myhome/Development/app/services/node_modules/node-forge/js/forge.js:59:1
        at Object.<anonymous> (/Users/myhome/Development/app/services/node_modules/node-forge/js/forge.js:92:3)
        at Module._compile (module.js:425:26)
        at Module.module.constructor._compile (/Users/myhome/Development/app/services/node_modules/amd-loader/amd-loader.js:10:31)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/Users/myhome/Development/app/services/node_modules/google-p12-pem/index.js:1:75)
        at Module._compile (module.js:425:26)
        at Module.module.constructor._compile (/Users/myhome/Development/app/services/node_modules/amd-loader/amd-loader.js:10:31)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/Users/myhome/Development/app/services/node_modules/gtoken/lib/index.js:1:77)
        at Module._compile (module.js:425:26)
        at Module.module.constructor._compile (/Users/myhome/Development/app/services/node_modules/amd-loader/amd-loader.js:10:31)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/Users/myhome/Development/app/services/node_modules/google-auth-library/lib/auth/jwtclient.js:20:14)
        at Module._compile (module.js:425:26)
        at Module.module.constructor._compile (/Users/myhome/Development/app/services/node_modules/amd-loader/amd-loader.js:10:31)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/Users/myhome/Development/app/services/node_modules/google-auth-library/lib/auth/googleauth.js:19:17)
        at Module._compile (module.js:425:26)
        at Module.module.constructor._compile (/Users/myhome/Development/app/services/node_modules/amd-loader/amd-loader.js:10:31)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17) `

**Comment by stephenplusplus** [comment]
This may be an issue `npm cache clean && npm install` can fix, but if not, try opening an issue on [`forge`](https://github.com/digitalbazaar/forge/issues). It is indirectly a dependency of this library. Please link back if you open an issue there, and provide your Node version and OS as those will likely be helpful in debugging.

**Comment by musicalshore** [comment]
I am using Node 5.0.0 and have tried gcloud 0.24.0, 0.25.1 and 0.28.0.

[Issue opened on `forge`.](https://github.com/digitalbazaar/forge/issues/362)
