### ISSUE TITLE
datastore: can not runQuery in a transaction

### ISSUE THREAD

**Issue by jasonswearingen** [GoogleCloudPlatform/gcloud-node#1138]
hello is running a query in a transaction supposed to be supported?   I get errors when doing so (invalid response), while running a query outside of transactions works fine, and reading+writing inside a transaction also works.

I'm trying to do a query with a filter "email ="  

sorry I can't provide you code, I do my datastore operations via a self-rolled orm.

**Comment by stephenplusplus** [comment]
It should work, as far as I know. What version of gcloud are you running? I'll try to reproduce.

**Comment by jasonswearingen** [comment]
thanks Stephen,  i'm using 0.27, since it's supposed to work, i'll do a repro and post it here in a few min.

**Comment by jasonswearingen** [comment]
here is my repro code:

```

			console.log("################## running datastore transaction query test");
			let key = dataset.key(["test", 123]);

			dataset.upsert({
				key: key,
				data: { email: "test@example.com" }
			}, (err, upsertResponse) => {

				if (err != null) {
					console.log("!!!!!!!!!!!!!!!!!!!!!!!! dataset.upsert err", err.message);
					throw err;
				}
				console.log("################## upsert complete");

				dataset.runInTransaction((transaction, done) => {

					let query = dataset.createQuery("test");
					query.filter("email =", "test@example.com");

					transaction.runQuery(query, (err, entities) => {

						if (err != null) {
							console.log("!!!!!!!!!!!!!!!!!!!!!!!! transaction.runQuery err",err.message);
							throw err;
						}

						console.log("################## transaction.runQuery complete");
						for (let i = 0; i < entities.length; i++) {
							let current = entities[i];
							console.log("################## entity " + i, current.key.path.join(), JSON.stringify(current.data));
						}

					});

				}, (err, transactionResponse) => {
					if (err != null) {
						console.log("!!!!!!!!!!!!!!!!!!!!!!!! transaction.runInTransaction err", err.message);
						throw err;
					}
					console.log("################## transaction.runInTransaction complete");

				});


			});
```

and here is my console output:

```
################## running datastore transaction query test
################## upsert complete
!!!!!!!!!!!!!!!!!!!!!!!! transaction.runQuery err Bad Request
ApiError: Bad Request
    at new util.ApiError (C:\repos\stage3\nlib\node_modules\gcloud\lib\common\util.js:92:10)
    at Object.parseHttpRespMessage (C:\repos\stage3\nlib\node_modules\gcloud\lib\common\util.js:134:33)
    at Request._callback (C:\repos\stage3\nlib\node_modules\gcloud\lib\datastore\request.js:813:31)
    at Request.self.callback (C:\repos\stage3\nlib\node_modules\request\request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\repos\stage3\nlib\node_modules\request\request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\repos\stage3\nlib\node_modules\request\request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
[ERROR] 07:59:27 ApiError
```

**Comment by stephenplusplus** [comment]
I ran this test with v0.28, which reports more helpful errors. Try updating just to make the experience a little better-- it will require one change:

```diff
-query.filter("email =", "test@example.com");
+query.filter("email", "test@example.com");
```

Anyway, because I upgraded and received the better error reporting, what I got was:

```
ApiError: Bad Request - queries inside transactions must have ancestors
```

There's a description of what that means here: https://cloud.google.com/appengine/docs/python/datastore/queries#queries_inside_transactions_must_include_ancestor_filters

See if with this information you can produce the desired results. If not, we can call for some more help :)

**Comment by jasonswearingen** [comment]
ok thanks, i don't know much about ancestors (have deliberately avoided them), so pretty sure none of my data uses them, so it looks like I can't query in transactions in my use-case.   It seems ok though (and probably better):  I worked around this by running my query first, and then run the transaction.

**Comment by stephenplusplus** [comment]
Cool! Let me know if there are any other questions or issues with this approach.
