### ISSUE TITLE
storage upload use /temp/ instead of /home/?

### ISSUE THREAD

**Issue by Eksrow** [GoogleCloudPlatform/gcloud-node#1235]
I'm on aws lambda trying to upload a file to gcs.
This line of code to upload a file: 

```
var bucket = gcs.bucket('biweekly.hylight.tv');
bucket.upload(tmpobj.name, {
		destination : uuidName + '.mp4',
		metadata : {
			contentType : 'video/mp4',
			name : uuidName + '.mp4'
		}
	});
```

Results in:
```
Error: EROFS: read-only file system, mkdir '/home/sbx_user1053

at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (/var/task/node_modules/gcloud/node_modules/gcs-resumable-upload/node_modules/configstore/node_modules/mkdirp/index.js:71:13)
    at sync (/var/task/node_modules/gcloud/node_modules/gcs-resumable-upload/node_modules/configstore/node_modules/mkdirp/index.js:77:24)
    at Function.sync (/var/task/node_modules/gcloud/node_modules/gcs-resumable-upload/node_modules/configstore/node_modules/mkdirp/index.js:77:24)
    at Object.create.all.get (/var/task/node_modules/gcloud/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:38:13)
    at Object.Configstore (/var/task/node_modules/gcloud/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:27:44)
    at new Upload (/var/task/node_modules/gcloud/node_modules/gcs-resumable-upload/index.js:48:22)
    at Upload (/var/task/node_modules/gcloud/node_modules/gcs-resumable-upload/index.js:26:41)
    at File.startResumableUpload_ (/var/task/node_modules/gcloud/lib/storage/file.js:1443:22)
```

So this is solved by setting resumable to false, which is great, but I was wondering if it was possible to change the cache(I assume it's cache) directory to something else like temp?

**Comment by stephenplusplus** [comment]
You can change the directory with an env var `XDG_CONFIG_HOME` (see #1051). Please re-open if this doesn't work.

**Comment by Eksrow** [comment]
Thank you.
