### ISSUE TITLE
Unexpected behavior with Vision API + GCS

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/gcloud-node#1326]
I suspect this is two separate issues, but the repro case happens to combine both so posting a combo issue here.

I'm putting together a demo that uses the Vision API to extract text, then saves this text to a GCS bucket.  This fails on two dimensions:

1. The text extracted from the image seems to repeat in a weird comma delimited addition
2. The `save` to GCS fails with an `Invalid non-string/buffer chunk` error.

Repro sample app included, as is the output I see from running this locally

(Change the relevant values like projectId in the sample below)

**Image**

![sample_en](https://cloud.githubusercontent.com/assets/764528/15348015/b411853a-1c7b-11e6-8ca0-46ad97cec395.png)

**Code**

```javascript
var gcloud = require('gcloud')({
	projectId: 'some-project',
	keyFilename: __dirname + '/keyfile.json'
});

var vision = gcloud.vision();

vision.detectText(__dirname + '/sample_en.png', function(err, text) {
	if (err) {
		console.error(err);
		return;
	}

	console.log(text);

	var file = gcloud.storage().bucket('some-bucket').file('output.txt');

	file.save(text, function(err) {
		if (err) {
			console.log(err.stack);
		}
	});
});
```

**package.json**

```javascript
{
  "name": "gcloud-tests",
  "version": "1.0.0",
  "description": "gcloud node tests",
  "main": "index.js",
  "author": "Jason Polites",
  "dependencies": {
    "gcloud": "^0.33.0"
  }
}
```

**Result**

```
[ 'When, in the course of human events, it\nbecomes necessary for one people to\ndissolve\nthe political bands which have\nconnected them\nwith another, and to assume among the powers\nof the earth, the separate and equal station to\nwhich the laws of nature and of nature\'s God\nentitle them, a decent respect to the opinions of\nmankind requires that they should declare the\ncauses which impel them to the separation.\nWe hold these truths to be self-evident, that all\nmen are created equal, that they are endowed\nby their Creator with certain unalienable rights,\nthat among these are life, liberty and the pursuit\nof happiness.\n',
  'When,',
  'in',
  'the',
  'course',
  'of',
  'human',
  'events,',
  'it',
  'becomes',
  'necessary',
  'for',
  'one',
  'people',
  'to',
  'dissolve',
  'the',
  'political',
  'bands',
  'which',
  'have',
  'connected',
  'them',
  'with',
  'another,',
  'and',
  'to',
  'assume',
  'among',
  'the',
  'powers',
  'of',
  'the',
  'earth,',
  'the',
  'separate',
  'and',
  'equal',
  'station',
  'to',
  'which',
  'the',
  'laws',
  'of',
  'nature',
  'and',
  'of',
  'nature\'s',
  'God',
  'entitle',
  'them,',
  'a',
  'decent',
  'respect',
  'to',
  'the',
  'opinions',
  'of',
  'mankind',
  'requires',
  'that',
  'they',
  'should',
  'declare',
  'the',
  'causes',
  'which',
  'impel',
  'them',
  'to',
  'the',
  'separation.',
  'We',
  'hold',
  'these',
  'truths',
  'to',
  'be',
  'self-evident,',
  'that',
  'all',
  'men',
  'are',
  'created',
  'equal,',
  'that',
  'they',
  'are',
  'endowed',
  'by',
  'their',
  'Creator',
  'with',
  'certain',
  'unalienable',
  'rights,',
  'that',
  'among',
  'these',
  'are',
  'life,',
  'liberty',
  'and',
  'the',
  'pursuit',
  'of',
  'happiness.' ]
TypeError: Invalid non-string/buffer chunk
    at validChunk (/Users/Jason/projects/sandbox/node_modules/readable-stream/lib/_stream_writable.js:218:14)
    at Writable.write (/Users/Jason/projects/sandbox/node_modules/readable-stream/lib/_stream_writable.js:239:53)
    at Duplexify.end (/Users/Jason/projects/sandbox/node_modules/duplexify/index.js:222:18)
    at File.save (/Users/Jason/projects/sandbox/node_modules/gcloud/lib/storage/file.js:1510:6)
    at /Users/Jason/projects/sandbox/index.js:18:7
    at /Users/Jason/projects/sandbox/node_modules/gcloud/lib/vision/index.js:427:7
    at /Users/Jason/projects/sandbox/node_modules/gcloud/lib/vision/index.js:158:5
    at Object.handleResp (/Users/Jason/projects/sandbox/node_modules/gcloud/lib/common/util.js:126:3)
    at /Users/Jason/projects/sandbox/node_modules/gcloud/lib/common/util.js:446:12
    at Request.onResponse [as _callback] (/Users/Jason/projects/sandbox/node_modules/retry-request/index.js:117:7)

```

**Comment by jasonpolites** [comment]
Closing.  RTFM
