### ISSUE TITLE
Error: grpc_node.node: invalid ELF header

### ISSUE THREAD

**Issue by Nabarun** [GoogleCloudPlatform/gcloud-node#1409]
I have a node.js app which is deployed in heroku. I am using gcloud to query vision related stuff. It works on my local but in heroku it throws following exception. Please help me to resolve this

```
2016-07-05T04:56:40.742299+00:00 app[web.1]: module.js:440
2016-07-05T04:56:40.742348+00:00 app[web.1]:   return process.dlopen(module, path._makeLong(filename));
2016-07-05T04:56:40.742354+00:00 app[web.1]:                  ^
2016-07-05T04:56:40.742355+00:00 app[web.1]: 
2016-07-05T04:56:40.742356+00:00 app[web.1]: Error: /app/node_modules/gcloud/node_modules/grpc/src/node/extension_binary/grpc_node.node: invalid ELF header
2016-07-05T04:56:40.742356+00:00 app[web.1]:     at Error (native)
2016-07-05T04:56:40.742357+00:00 app[web.1]:     at Object.Module._extensions..node (module.js:440:18)
2016-07-05T04:56:40.742358+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-07-05T04:56:40.742358+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-07-05T04:56:40.742359+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-07-05T04:56:40.742359+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-07-05T04:56:40.742360+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/gcloud/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
2016-07-05T04:56:40.742361+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-07-05T04:56:40.742361+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-07-05T04:56:40.742362+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-07-05T04:56:40.723358+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/getlogo?url=http://i.forbesimg.com/media/lists/companies/coca-cola_416x416.jpg" host=runu.herokuapp.com request_id=92c7b1f8-be1c-4009-b2a9-73ac8adf81fe fwd="71.202.43.114" dyno=web.1 connect=1ms service=1350ms status=503 bytes=0
2016-07-05T04:56:41.531276+00:00 heroku[web.1]: Process exited with status 1
2016-07-05T04:56:41.516318+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by Nabarun** [comment]
node --version
v4.4.1

**Comment by stephenplusplus** [comment]
This issue was moved to grpc/grpc#7236
