### ISSUE TITLE
TypeError: Cannot call method 'map' of undefined

### ISSUE THREAD

**Issue by mahtuag** [GoogleCloudPlatform/gcloud-node#424]
I setup an instance of type f1-micro in us-central1-f data center (machine type Ivy Bridge) running CentOS 7 to test some of my queries on as I plan to use google datastore as the backend db for a project.

The other details are that I enabled datastore service both for the project and for the instance while creating it.

Ran the following commands to update the system and get node running:

```bash
sudo yum install epel-release
sudo yum install vim git nodejs npm screen
sudo yum update
npm install gcloud
vim app.js
```

Dumped the following code into app.js:

```javascript
'use strict';                                                                   
console.log('Entered app');                                                     
var gcloud = require('gcloud');                                                 
console.log('Imported gcloud');                                                 
var db = gcloud.datastore.dataset({                                        
  projectId: "<my actual project ID>"                                                
});                                                                             
var phone = '000000';                                                    
var userExistenceCheckQuery = {                                                 
  kinds: [{name: 'User'}],                                                      
  filter: {                                                                     
    propertyFilter: {                                                           
      property: {name: 'phone'},                                                
      operator: 'EQUAL',                                                        
      value: {stringValue: phone}                                               
    }                                                                           
  }                                                                             
};                                                                              
db.runQuery({                                                            
    query: userExistenceCheckQuery,                                             
  }).execute(function(err, result) {                                            
    if(err) {console.log(JSON.stringify(err, null, '  '));}                     
    else {console.log(JSON.stringify(result, null, '  '));}                     
  });
```

Output:
```
Entered app
Imported gcloud

/home/gautham/node_modules/gcloud/lib/datastore/entity.js:542
  query.projection = q.selectVal.map(function(v) {
                                 ^
TypeError: Cannot call method 'map' of undefined
    at Object.queryToQueryProto (/home/gautham/node_modules/gcloud/lib/datastore/entity.js:542:34)
    at Dataset.DatastoreRequest.runQuery (/home/gautham/node_modules/gcloud/lib/datastore/request.js:375:19)
    at Object.<anonymous> (/home/gautham/app.js:19:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Other relevant information:

node.js version is v0.10.33

Is there something I am doing wrong or is this a bug in the library ?

**Comment by stephenplusplus** [comment]
This looks like code that the google-apis library expects (@ryanseys?)

This same thing in our library should look something like:

```js
'use strict';
console.log('Entered app');
var gcloud = require('gcloud');
console.log('Imported gcloud');
var db = gcloud.datastore.dataset({
  projectId: "<my actual project ID>"
});
var phone = '000000';
var userExistenceCheckQuery = db
  .createQuery('User')
  .filter('phone =', phone);

db.runQuery(userExistenceCheckQuery, function(err, result) {
  if(err) {console.log(JSON.stringify(err, null, '  '));}
  else {console.log(JSON.stringify(result, null, '  '));}
});
```

**Comment by stephenplusplus** [comment]
Feel free to re-open if you have any issues with our API. (Docs here: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.12.0/datastore/query)

**Comment by ryanseys** [comment]
Yeah the generic library ([`google-api-nodejs-client`](https://github.com/google/google-api-nodejs-client)) accepts this more generic form of a query object. Within `gcloud-node` we try to maintain a more idiomatic approach which is the reason for the simplified api. Hope you find you like it more than the generic library! :)
