### ISSUE TITLE
pubsub error - Cannot read property 'onAuthorized' of undefined

### ISSUE THREAD

**Issue by leibale** [GoogleCloudPlatform/gcloud-node#466]
```
Cannot read property 'onAuthorized' of undefined,

TypeError: Cannot read property 'onAuthorized' of undefined
    at onAuthorizedRequest (/home/leibale/workspace/images-processor/node_modules/gcloud/lib/common/util.js:397:19)
    at /home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/google-service-account/connection.js:56:5
    at Connection.<anonymous> (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/google-service-account/connection.js:116:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by stephenplusplus** [comment]
What version of gcloud are you using? If not master, would you mind testing against that, as we have made significant changes since 0.12.0 was released back in December.

**Comment by leibale** [comment]
ok, now it's working.
thanks.

**Comment by stephenplusplus** [comment]
Phew!

**Comment by leibale** [comment]
@stephenplusplus I got this error again
```
Cannot read property 'onAuthorized' of undefined,

TypeError: Cannot read property 'onAuthorized' of undefined
    at onAuthorizedRequest (/home/leibale/workspace/images-processor/node_modules/gcloud/lib/common/util.js:478:19)
    at /home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/google-service-account/connection.js:56:5
    at Connection.<anonymous> (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/google-service-account/connection.js:116:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by ryanseys** [comment]
Is there some method you are calling where you aren't specifying a callback?

**Comment by leibale** [comment]
only ```file.createReadStream()``` and ```file.createWriteStream()```, but i listen to err and finish events

**Comment by ryanseys** [comment]
Ok! If you have a small snippet we could run to reproduce this it would greatly speed up tracking down the bug. That line throwing the error is used by every api request.

**Comment by leibale** [comment]
i using ```file.createWriteStream()```, ```file.createReadStream()```, ```subscription.pull()```.
i think it's from ```subscription.pull()```, but..

**Comment by leibale** [comment]
it's happening on ```subscription.ack(result.id);```

**Comment by leibale** [comment]
ok, i'ts
