### ISSUE TITLE
pubsub: unhelpful error message when trying to publish a string.

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/gcloud-node#500]
When I do the following:

```javascript
topic.publish('New message!', function(err) }
}
```

I get:

```
buffer.js:188
        throw new TypeError('First argument needs to be a number, ' +
              ^
TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:188:15)
    at Topic.formatMessage_ (/usr/local/google/home/tmatsuo/node_modules/gcloud/lib/pubsub/topic.js:80:20)
    at Array.map (native)
    at Topic.publish (/usr/local/google/home/tmatsuo/node_modules/gcloud/lib/pubsub/topic.js:183:24)
    at null._onTimeout (/usr/local/google/home/tmatsuo/tmp/mayran/mysubscribe.js:44:27)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

Under the cover, the code is trying to make message.data (which is undefined) a buffer:

```javascript
Topic.formatMessage_ = function(message) {
  if (!util.is(message.data, 'buffer')) {
    message.data = new Buffer(JSON.stringify(message.data));
  }

  message.data = message.data.toString('base64');

  return message;
};
```

Maybe type check first and give helpful error messages?

**Comment by stephenplusplus** [comment]
Good idea. PR sent!
