### ISSUE TITLE
Could not install `gcloud-node` with iojs v2.0.1 & npm v2.9.1

### ISSUE THREAD

**Issue by dmtrs** [GoogleCloudPlatform/gcloud-node#626]
Got error by running:  `npm install --save gcloud-node`

I also opened an issue to [Voxer/sse4_crc32#30](https://github.com/Voxer/sse4_crc32/issues/30)

```
➜  gcloud-test git:(gcloud) ✗ npm install --save gcloud
npm WARN package.json gcloud-test@0.0.1 No repository field.
npm WARN package.json gcloud-test@0.0.1 No README data
npm WARN package.json node-config@0.0.2 No repository field.
npm WARN package.json node-config@0.0.2 Invalid filename in 'files' list:

> sse4_crc32@3.1.2 install /home/user/code/gcloud-test/node_modules/gcloud/node_modules/sse4_crc32
> > node-gyp rebuild
> >
> > gyp WARN install got an error, rolling back install
> > gyp ERR! configure error
> > gyp ERR! stack Error: 404 status code downloading tarball
> > gyp ERR! stack     at Request.<anonymous> (/home/user/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
> > gyp ERR! stack     at emitOne (events.js:82:20)
> > gyp ERR! stack     at Request.emit (events.js:166:7)
> > gyp ERR! stack     at Request.onRequestResponse (/home/user/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/node_modules/request/request.js:1156:10)
> > gyp ERR! stack     at emitOne (events.js:77:13)
> > gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
> > gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:414:21)
> > gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
> > gyp ERR! stack     at Socket.socketOnData (_http_client.js:304:20)
> > gyp ERR! stack     at emitOne (events.js:77:13)
> > gyp ERR! System Darwin 14.0.0
> > gyp ERR! command "/home/user/.nvm/versions/io.js/v2.0.1/bin/iojs" "/home/user/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> > gyp ERR! cwd /home/user/code/gcloud-test/node_modules/gcloud/node_modules/sse4_crc32
> > gyp ERR! node -v v2.0.1
> > gyp ERR! node-gyp -v v1.0.3
> > gyp ERR! not ok
> > npm ERR! Darwin 14.0.0
> > npm ERR! argv "/home/user/.nvm/versions/io.js/v2.0.1/bin/iojs" "/home/user/.nvm/versions/io.js/v2.0.1/bin/npm" "install" "--save" "gcloud"
> > npm ERR! node v2.0.1
> > npm ERR! npm  v2.9.1
> > npm ERR! code ELIFECYCLE
> >
> > npm ERR! sse4_crc32@3.1.2 install: `node-gyp rebuild`
> > npm ERR! Exit status 1
> > npm ERR!
> > npm ERR! Failed at the sse4_crc32@3.1.2 install script 'node-gyp rebuild'.
> > npm ERR! This is most likely a problem with the sse4_crc32 package,
> > npm ERR! not with npm itself.
> > npm ERR! Tell the author that this fails on your system:
> > npm ERR!     node-gyp rebuild
> > npm ERR! You can get their info via:
> > npm ERR!     npm owner ls sse4_crc32
> > npm ERR! There is likely additional logging output above.
> >
> > npm ERR! Please include the following file with any support request:
> > npm ERR!     /home/user/code/gcloud-test/npm-debug.log
> > ➜  gcloud-test git:(gcloud) ✗ vim npm-debug.log
> > ➜  gcloud-test git:(gcloud) ✗ rm -rf npm-debug.log
> > ➜  gcloud-test git:(gcloud) ✗ npm install --save gcloud
> > npm WARN package.json gcloud-test@0.0.1 No repository field.
> > npm WARN package.json gcloud-test@0.0.1 No README data
> > npm WARN package.json node-config@0.0.2 No repository field.
> > npm WARN package.json node-config@0.0.2 Invalid filename in 'files' list:
> >
> > > sse4_crc32@3.1.2 install /home/user/code/gcloud-test/node_modules/gcloud/node_modules/sse4_crc32
> > > > node-gyp rebuild
> > > >
> > > > gyp WARN install got an error, rolling back install
> > > > gyp ERR! configure error
> > > > gyp ERR! stack Error: 404 status code downloading tarball
> > > > gyp ERR! stack     at Request.<anonymous> (/home/user/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
> > > > gyp ERR! stack     at emitOne (events.js:82:20)
> > > > gyp ERR! stack     at Request.emit (events.js:166:7)
> > > > gyp ERR! stack     at Request.onRequestResponse (/home/user/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/node_modules/request/request.js:1156:10)
> > > > gyp ERR! stack     at emitOne (events.js:77:13)
> > > > gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
> > > > gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:414:21)
> > > > gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
> > > > gyp ERR! stack     at Socket.socketOnData (_http_client.js:304:20)
> > > > gyp ERR! stack     at emitOne (events.js:77:13)
> > > > gyp ERR! System Darwin 14.0.0
> > > > gyp ERR! command "/home/user/.nvm/versions/io.js/v2.0.1/bin/iojs" "/home/user/.nvm/versions/io.js/v2.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> > > > gyp ERR! cwd /home/user/code/gcloud-test/node_modules/gcloud/node_modules/sse4_crc32
> > > > gyp ERR! node -v v2.0.1
> > > > gyp ERR! node-gyp -v v1.0.3
> > > > gyp ERR! not ok
> > > > npm ERR! Darwin 14.0.0
> > > > npm ERR! argv "/home/user/.nvm/versions/io.js/v2.0.1/bin/iojs" "/home/user/.nvm/versions/io.js/v2.0.1/bin/npm" "install" "--save" "gcloud"
> > > > npm ERR! node v2.0.1
> > > > npm ERR! npm  v2.9.1
> > > > npm ERR! code ELIFECYCLE
> > > >
> > > > npm ERR! sse4_crc32@3.1.2 install: `node-gyp rebuild`
> > > > npm ERR! Exit status 1
> > > > npm ERR!
> > > > npm ERR! Failed at the sse4_crc32@3.1.2 install script 'node-gyp rebuild'.
> > > > npm ERR! This is most likely a problem with the sse4_crc32 package,
> > > > npm ERR! not with npm itself.
> > > > npm ERR! Tell the author that this fails on your system:
> > > > npm ERR!     node-gyp rebuild
> > > > npm ERR! You can get their info via:
> > > > npm ERR!     npm owner ls sse4_crc32
> > > > npm ERR! There is likely additional logging output above.
> > > >
> > > > npm ERR! Please include the following file with any support request:
> > > > npm ERR!     /home/user/code/gcloud-test/npm-debug.log
```

**Comment by ryanseys** [comment]
Hi I tried to reproduce this on my machine and it took a long time to install (might be terrible wifi here in this tim hortons) but it did succeed so I'm curious if you can continue to reproduce this or if it was an intermittent error? Looking at the log it makes mention to a 404 error so maybe a resource was unavailable temporarily. 

Can you also post what machine you are running this on here and on Voxer/sse4_crc32#30 so we can help diagnose the issue further?

Thanks!

**Comment by dmtrs** [comment]
Moved to `iojs v.2.1.0` and system update resolved the issue
