### ISSUE TITLE
Reading a nonexisting file succeeds

### ISSUE THREAD

**Issue by marekbiskup** [GoogleCloudPlatform/gcloud-node#772]
I tried to open an nonexisting file. It succeeded and gave me the following contents:

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>
```

I'd prefer the function threw an exception of called 'error'.

My code
```
  var content = '';
  var readStream = bucket.file(data.name).createReadStream();
  readStream.on('data', function(buf) { content += buf.toString(); });
  readStream.on('end', function() {
    console.log("got file data: " + content);
  });
  readStream.on('error', function(err) {
    console.log("Error opening a gcs file " + data.name + ": " + err)
  });
```

output:
got file data: <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>

EDIT: I actually also got an error message, see below.

**Comment by marekbiskup** [comment]
Sorry, I must have overlooked the log message:

```
Error opening a gcs file triggers/gcsfile-VjpUNk.json: Error: Error during request.
```

So everything is fine. I'm just surprised I also got some content.
This is probably FAD.

**Comment by stephenplusplus** [comment]
I think this is worth taking a look at. I received an error while running some tests that probably relates:

```
  1) storage sign urls should create a signed read url:
     Uncaught AssertionError: '<?xml version=\'1.0\' encoding=\'UTF-8\'?><Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><De == <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 fb 00 00 00 aa 08 06 00 00 00 6b a0 39 f4 00 00 00 19 74 45 58
      at Request._callback (system-test/storage.js:911:18)
      at _stream_readable.js:908:16
```

Thanks for opening the issue!
