### ISSUE TITLE
"Backend Error" when setting file ACL

### ISSUE THREAD

**Issue by knation** [GoogleCloudPlatform/gcloud-node#794]
Trying to set ACL after uploading and consistently getting a "Backend Error" when trying to set ACL. File uploads fine each time.

```javascript
var image = myBucket.file('foo.jpg');
var imageWriteStream = image.createWriteStream({ contentType: 'image/jpeg' });

imageWriteStream.on('complete', function() {
  // Set ACL
  image.acl.add({
    scope: 'allUsers',
    role:  gcloud.storage.acl.READER_ROLE
  }, function(err) {
    // FAILING HERE
    console.log(err);
  });
});

my Stream.pipe(imageWriteStream);
```

**Comment by stephenplusplus** [comment]
Thanks for reporting, I'll check it out!

Just confirming, are you on gcloud version 0.18?

**Comment by knation** [comment]
Sorry about that. No, I'm on v0.15.0. The version installed through NPM. Is there an ETA of when v0.18 will be in NPM?

**Comment by stephenplusplus** [comment]
It's actually out now. What value do you have in your package.json?

**Comment by knation** [comment]
My bad. I must have previously installed it so it was stuck on v0.15. I updated and the problem persists.

**Comment by stephenplusplus** [comment]
Is the messaging still `Backend error`? We actually changed how errors are patched from the API - maybe it's more helpful this time around. At the very least, it should be "Error during request".

**Comment by knation** [comment]
```
Error: Backend Error
    at Object.parseApiResp (/Users/kirk/Projects/slashpath/src/node_modules/gcloud/lib/common/util.js:184:22)
    at Object.handleResp (/Users/kirk/Projects/slashpath/src/node_modules/gcloud/lib/common/util.js:139:25)
    at /Users/kirk/Projects/slashpath/src/node_modules/gcloud/lib/common/util.js:572:12
    at Request.onResponse [as _callback] (/Users/kirk/Projects/slashpath/src/node_modules/gcloud/node_modules/retry-request/index.js:107:7)
    at Request.self.callback (/Users/kirk/Projects/slashpath/src/node_modules/gcloud/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/kirk/Projects/slashpath/src/node_modules/gcloud/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/kirk/Projects/slashpath/src/node_modules/gcloud/node_modules/request/request.js:1003:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by stephenplusplus** [comment]
Oops, I just noticed we have incorrect docs. The parameter to use is actually `entity` instead of `scope`. Not sure that will be the fix here, but let's hope :crossed_flags:

**Comment by knation** [comment]
Hey, that was it, thanks!
