### ISSUE TITLE
Error in storage - calling transform done when ws.length != 0

### ISSUE THREAD

**Issue by leibale** [GoogleCloudPlatform/gcloud-node#805]
```
/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:204
    throw new Error('calling transform done when ws.length != 0');
          ^
Error: calling transform done when ws.length != 0
    at done (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:204:11)
    at DestroyableTransform.<anonymous> (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:139:7)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at DestroyableTransform.<anonymous> (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/stream-forward/index.js:31:26)
    at DestroyableTransform.<anonymous> (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/stream-forward/node_modules/on-everything/index.js:12:17)
    at DestroyableTransform.obj.(anonymous function) [as emit] (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/stream-forward/node_modules/stubs/index.js:28:10)
    at finishMaybe (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/retry-request/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:502:14)
    at endWritable (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/retry-request/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:512:3)
    at DestroyableTransform.Writable.end (/home/leibale/workspace/images-processor/node_modules/gcloud/node_modules/retry-request/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:477:5)
```

i don't know the exact request- but it's from the storage

**Comment by stephenplusplus** [comment]
Thanks for reporting. If you can zero in on one or more of your gcloud calls that consistently produces this, that would definitely help. But, generally speaking, our streams do need some safeguards to prevent again this.

**Comment by leibale** [comment]
```javascript
file.download({
  destination: path
}, function (err) {
// --
/});
```
this is the request

**Comment by leibale** [comment]
it's important so.. i will be happy if somebody help me

**Comment by stephenplusplus** [comment]
Sure, we'll do our best. Your best option for now is probably to downgrade to v0.17.

**Comment by leibale** [comment]
It also does not work

**Comment by stephenplusplus** [comment]
Ok, roll back once more to 0.16 or the soonest you are able to make the request successfully.

**Comment by leibale** [comment]
but in v0.16 the maxInProgress doesn't exist

----------

maybe it's happened after change in the server

"On June 9th your project XXXXXXXX was affected by an incident which caused elevated error rates for 1 hour 40 minutes. You can read about the incident and the changes we have made to prevent re-occurrence at https://status.cloud.google.com/incident/storage/16025.

We take such incidents seriously and are therefore issuing a credit under the terms of our Service Level Agreement (SLA) as defined at https://cloud.google.com/storage/sla. This credit will be equal to 10% of your June Google Cloud Storage bill. In this case, we will apply this credit to your account automatically, bypassing the normal SLA application procedure, so no action is required on your part.

Yours,
The Google Cloud Storage Team

Google Inc. 1600 Amphitheatre Parkway, Mountain View, CA 94043

You have received this mandatory service announcement to update you about important changes to Google Cloud Platform or your account.

i got this in email from CloudPlatform-noreply@google.com

**Comment by stephenplusplus** [comment]
Can you try removing the node_modules directory and re-installing gcloud? I updated the problematic dependency here: https://github.com/stephenplusplus/stream-forward/commit/11ec2a76931cb6a9d9ebf541ed100d501ce54eb6

**Comment by leibale** [comment]
re-installing gcloud from github or from npm?

**Comment by stephenplusplus** [comment]
From npm, it will automatically pick up the new stream-forward. Just make sure to rm -rf node_modules first. Updating is weird.

**Comment by leibale** [comment]
now requests not returns (and i am in google vm so it's not internet problem)

**Comment by stephenplusplus** [comment]
All requests aren't returning? Can you show more of the code you're using?

**Comment by leibale** [comment]
```
file.download({
  destination: path
}, function (err) {
// --
/});
```

**Comment by leibale** [comment]
sorry, the code is:
```javascript
storage.backupBucket.file(message.filename).createReadStream().on('error', callback).pipe(fs.createWriteStream(path)).on('finish', function () {
  console.log('downloaded');
  callback(null, message, path);
});
```

**Comment by stephenplusplus** [comment]
Ah, thanks-- I see now! You need to listen for the `complete` event, instead of `finish`.

**Comment by stephenplusplus** [comment]
Oh, I'm sorry, I misread the code. BRB :)

**Comment by leibale** [comment]
you need help?

**Comment by stephenplusplus** [comment]
PR with a fix is coming shortly... basically, we destroy the stream. We don't have to do that unless there's an error.

**Comment by stephenplusplus** [comment]
PR sent! #809
