### ISSUE TITLE
unable to install from npm on debian

### ISSUE THREAD

**Issue by stellanhaglund** [GoogleCloudPlatform/gcloud-node#866]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Linux 3.16.0-0.bpo.4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node_modules/gcloud/node_modules/hash-stream-validation/node_modules/s
se4_crc32
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.16.0-0.bpo.4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! sse4_crc32@4.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sse4_crc32@4.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sse4_crc32 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sse4_crc32
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:

**Comment by stellanhaglund** [comment]
sorry I was missing make.
